name: Butler release

on:
  workflow_dispatch:

jobs:

  butlerPush:
    runs-on: ubuntu-20.04

    steps:

    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        ./butler -v

    - name: Check versions
      env:
            BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
      run: |
        source version.sh
        tag="v$PRODUCT-$MAJOR.$MINOR.$PATCH"
        echo $tag

        wget https://github.com/JerboaBurrow/Stellar/releases/download/$tag/Stellar-android.zip
        ./butler push Stellar-android.zip Jerboa-app/jelly-cram:android --userversion $PRODUCT-$MAJOR.$MINOR.$PATCH

        wget https://github.com/JerboaBurrow/Stellar/releases/download/$tag/Stellar-windows.zip
        ./butler push Stellar-windows.zip Jerboa-app/jelly-cram:windows --userversion $PRODUCT-$MAJOR.$MINOR.$PATCH
        
        mkdir linux
        wget https://github.com/JerboaBurrow/Stellar/releases/download/$tag/Stellar-linux-x86_64.tar.xz
        tar -xvJf Stellar-linux-x86_64.tar.xz -C linux
        cd linux && zip -r ../Stellar-linux-x86_64.zip . && cd ..
        ./butler push Stellar-linux-x86_64.zip Jerboa-app/jelly-cram:linux --userversion $PRODUCT-$MAJOR.$MINOR.$PATCH

        mkdir macos
        wget https://github.com/JerboaBurrow/Stellar/releases/download/$tag/Stellar-macOS.tar.xz
        tar -xvJf Stellar-macOS.tar.xz -C macos
        cd macos && zip -r ../Stellar-macOS.zip . && cd ..
        ./butler push Stellar-macOS.zip Jerboa-app/jelly-cram:macOS --userversion $PRODUCT-$MAJOR.$MINOR.$PATCH
        